export interface ServiceData {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
  fullDescription: string;
  fullDescriptionEn: string;
  icon: string;
  category: string;
  categoryAr: string;
  price: number;
  priceNote: string;
  priceNoteEn: string;
  duration: string;
  durationEn: string;
  features: string[];
  featuresEn: string[];
  requirements: string[];
  requirementsEn: string[];
  steps: { title: string; description: string; icon: string }[];
  stepsEn: { title: string; description: string; icon: string }[];
  faq: { question: string; answer: string }[];
  faqEn: { question: string; answer: string }[];
  requiredDocuments: string[];
  requiredDocumentsEn: string[];
  isPopular: boolean;
  isActive: boolean;
  gradient: string;
}

export const servicesData: ServiceData[] = [
  {
    id: 'visa-tourist',
    name: 'تأشيرة سياحية',
    nameEn: 'Tourist Visa',
    description: 'خدمة استخراج التأشيرة السياحية للسعوديين والسياح الأجانب. نتولى جميع الإجراءات اللازمة للحصول على التأشيرة بأسرع وقت ممكن.',
    descriptionEn: 'Tourist visa issuance for Saudis and foreign tourists. We handle all procedures quickly.',
    fullDescription: 'نقدم لكم خدمة استخراج التأشيرة السياحية بشكل احترافي وسريع يضمن لكم الحصول على تأشيرتكم دون أي تعقيدات. نتعامل مع جميع الجنسيات ونوفر استشارة مجانية لاختيار نوع التأشيرة المناسب لوجهتكم.\n\nفريقنا المتميز يتابع طلبكم خطوة بخطوية من تاريخ التقديم وحتى استلام التأشيرة. نمتلك علاقات قوية مع السفارات والقنصليات المختلفة مما يسرّع عملية الموافقة.\n\nنلتزم بأعلى معايير الجودة والشفافية في التعامل، ونقدم ضمان استرداد المبلغ في حال عدم الحصول على الموافقة.\n\nالخدمة متاحة على مدار أيام الأسبوع ونسعى دائماً لتوفير تجربة سلسة ومريحة لعملائنا الكرام.',
    fullDescriptionEn: 'Professional and fast tourist visa issuance with money-back guarantee and 24/7 support.',
    icon: 'Globe',
    category: 'VISAS',
    categoryAr: 'التأشيرات',
    price: 250,
    priceNote: 'يبدأ من',
    priceNoteEn: 'Starting from',
    duration: '3-5 أيام عمل',
    durationEn: '3-5 business days',
    features: ['استخراج سريع وموثوق', 'متابعة مستمرة حتى الاستلام', 'دعم فني على مدار الساعة', 'ضمان استرداد المبلغ', 'استشارة مجانية أولية', 'تعامل مع جميع الجنسيات'],
    featuresEn: ['Fast and reliable', 'Continuous follow-up', '24/7 support', 'Money-back guarantee', 'Free consultation', 'All nationalities'],
    requirements: ['جواز سفر ساري المفعول لمدة 6 أشهر', 'صور شخصية بمواصفات الختم', 'حجز فندق مؤكد', 'تذكرة طيران ذهاب وعودة'],
    requirementsEn: ['Passport valid 6 months', 'Photos per specifications', 'Confirmed hotel booking', 'Round-trip ticket'],
    steps: [
      { title: 'تقديم الطلب', description: 'قم بتعبئة نموذج الطلب ورفع المستندات المطلوبة', icon: 'FileText' },
      { title: 'مراجعة المستندات', description: 'يقوم فريقنا بمراجعة مستنداتك والتأكد من صحتها', icon: 'CheckCircle' },
      { title: 'تقديم للسفارة', description: 'نقدم طلبك للسفارة أو القنصلية المختصة مباشرة', icon: 'Send' },
      { title: 'متابعة وتسليم', description: 'نتابع حالة الطلب حتى صدور التأشيرة ونسلمها لك', icon: 'Package' },
    ],
    stepsEn: [
      { title: 'Submit Request', description: 'Fill out the form and upload required documents', icon: 'FileText' },
      { title: 'Review Documents', description: 'Our team reviews your documents for accuracy', icon: 'CheckCircle' },
      { title: 'Submit to Embassy', description: 'We submit to the relevant embassy directly', icon: 'Send' },
      { title: 'Follow-up & Delivery', description: 'Track until visa issuance and deliver to you', icon: 'Package' },
    ],
    faq: [
      { question: 'كم تستغرق عملية استخراج التأشيرة السياحية؟', answer: 'عادة من 3 إلى 5 أيام عمل، وقد تختلف حسب الجنسية والوجهة.' },
      { question: 'هل تضمنون الحصول على التأشيرة؟', answer: 'نقدم ضمان استرداد المبلغ كاملاً في حال عدم الموافقة.' },
      { question: 'ما هي المستندات المطلوبة؟', answer: 'جواز سفر ساري وصور شخصية وحجز فندق وتذكرة طيران.' },
      { question: 'هل يمكنني تتبع حالة طلبي؟', answer: 'نعم، من خلال منصة التتبع أو التواصل مع فريق الدعم.' },
      { question: 'هل تتعاملون مع جميع الجنسيات؟', answer: 'نعم، نتعامل مع جميع الجنسيات مع استشارة مجانية.' },
    ],
    faqEn: [
      { question: 'How long does a tourist visa take?', answer: 'Usually 3-5 business days, varying by nationality and destination.' },
      { question: 'Do you guarantee approval?', answer: 'Full refund if not approved.' },
      { question: 'What documents are needed?', answer: 'Valid passport, photos, hotel booking, round-trip ticket.' },
      { question: 'Can I track my application?', answer: 'Yes, via our tracking platform or support team.' },
      { question: 'Do you handle all nationalities?', answer: 'Yes, with free consultation.' },
    ],
    requiredDocuments: ['جواز سفر ساري المفعول (6 أشهر على الأقل)', 'صور شخصية بخلفية بيضاء (4 صور)', 'كشف حساب بنكي آخر 3 أشهر', 'حجز فندق مؤكد', 'تذكرة طيران أولية أو مؤكدة'],
    requiredDocumentsEn: ['Valid passport (min 6 months)', '4 white-background photos', 'Bank statement (last 3 months)', 'Confirmed hotel booking', 'Flight ticket'],
    isPopular: true,
    isActive: true,
    gradient: 'from-[#2580eb] via-[#3b8cf6] to-[#60a5fa]',
  },
  {
    id: 'visa-business',
    name: 'تأشيرة عمل',
    nameEn: 'Business Visa',
    description: 'استخراج تأشيرة العمل للمقيمين والزوار بهدف ممارسة الأعمال التجارية والنشاطات المختلفة.',
    descriptionEn: 'Business visa issuance for commercial activities and business purposes.',
    fullDescription: 'نقدم خدمة استخراج تأشيرة العمل بشكل متكامل يشمل استشارة متخصصة وتجهيز جميع المستندات والتقديم المباشر للجهات المعنية.\n\nفريقنا من الخبراء يضمن تقديماً احترافياً يزيد من فرص الموافقة. نتعامل مع جميع أنواع تأشيرة العمل بما فيها تأشيرات المناسبات التجارية والمؤتمرات.\n\nنوفر متابعة شاملة من لحظة التقديم وحتى الاستلام مع إشعارات فورية بأي تحديثات. كما نقدم خدمات الترجمة والتصديق.\n\nنسعى دائماً لتقديم تجربة مميزة تتجاوز توقعات عملائنا.',
    fullDescriptionEn: 'Comprehensive business visa with specialized consultation and document preparation.',
    icon: 'Briefcase',
    category: 'VISAS',
    categoryAr: 'التأشيرات',
    price: 500,
    priceNote: 'يبدأ من',
    priceNoteEn: 'Starting from',
    duration: '5-7 أيام عمل',
    durationEn: '5-7 business days',
    features: ['استشارة مجانية أولية', 'تجهيز كامل للمستندات', 'تقديم السيرة الذاتية', 'متابعة حتى الاستلام', 'ترجمة المستندات', 'دعم متعدد اللغات'],
    featuresEn: ['Free consultation', 'Full document preparation', 'CV preparation', 'Follow-up to delivery', 'Document translation', 'Multi-language support'],
    requirements: ['جواز سفر ساري المفعول', 'خطاب رسمي من الشركة الداعية', 'عقد العمل أو العمل الحر', 'صور شخصية حديثة'],
    requirementsEn: ['Valid passport', 'Invitation letter from company', 'Work contract', 'Recent photos'],
    steps: [
      { title: 'الاستشارة الأولية', description: 'نحدد نوع التأشيرة المناسب ومتطلباتها', icon: 'MessageSquare' },
      { title: 'تجهيز المستندات', description: 'نحضر جميع المستندات وفقاً للمواصفات الرسمية', icon: 'FileText' },
      { title: 'تقديم الطلب', description: 'نقدم للسفارة مع جميع المستندات المطلوبة', icon: 'Send' },
      { title: 'المتابعة والتحديث', description: 'نتابع المستمر ونبلّغك بأي مستندات إضافية', icon: 'Bell' },
      { title: 'استلام التأشيرة', description: 'نسلم التأشيرة الجاهزة مع جميع التفاصيل', icon: 'Package' },
    ],
    stepsEn: [
      { title: 'Consultation', description: 'Determine appropriate visa type and requirements', icon: 'MessageSquare' },
      { title: 'Prepare Documents', description: 'Prepare all documents per official specs', icon: 'FileText' },
      { title: 'Submit Application', description: 'Submit to embassy with all documents', icon: 'Send' },
      { title: 'Follow-up', description: 'Track and notify of any additional needs', icon: 'Bell' },
      { title: 'Receive Visa', description: 'Deliver completed visa with all details', icon: 'Package' },
    ],
    faq: [
      { question: 'هل أحتاج لحضور شخصي للسفارة؟', answer: 'في معظم الحالات لا حاجة للحضور، يتولى فريقنا الإجراءات.' },
      { question: 'ما هي تكلفة تأشيرة العمل؟', answer: 'تبدأ من 500 ر.س شاملة المستندات والتقديم والمتابعة.' },
      { question: 'هل يمكن تحويل تأشيرة السياحة لعمل؟', answer: 'نعم، يمكننا مساعدتك في التحويل وفقاً للإجراءات الرسمية.' },
    ],
    faqEn: [
      { question: 'Do I need to attend personally?', answer: 'In most cases, no. Our team handles all procedures.' },
      { question: 'What is the cost?', answer: 'Starting from 500 SAR including documents, submission, and follow-up.' },
      { question: 'Can I convert tourist to business visa?', answer: 'Yes, we help with conversion through official procedures.' },
    ],
    requiredDocuments: ['جواز سفر ساري المفعول (12 شهر على الأقل)', 'خطاب دعوة من الشركة المستضيفة', 'سجل تجاري للشركة الداعية', 'صور شخصية بمواصفات الختم', 'خطاب من جهة العمل الحالية'],
    requiredDocumentsEn: ['Valid passport (min 12 months)', 'Invitation letter', 'Company commercial registration', 'Stamp-spec photos', 'Current employer letter'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#2580eb] via-[#1d4ed8] to-[#3b82f6]',
  },
  {
    id: 'visa-transit',
    name: 'تأشيرة عبور',
    nameEn: 'Transit Visa',
    description: 'خدمة استخراج تأشيرة العبور للمسافرين عبر المملكة العربية السعودية في طريقهم إلى وجهة أخرى.',
    descriptionEn: 'Transit visa for travelers passing through Saudi Arabia.',
    fullDescription: 'نوفر خدمة تأشيرة العبور بسرعة وكفاءة عالية للمسافرين عبر أراضي المملكة.whether في طريقكم إلى وجهة أخرى أو تخططون للتوقف القصير، نحن هنا لتسهيل إجراءاتكم.\n\nفريقنا يتابع طلباتكم بشكل فوري ويهتم بتسريع الموافقة لضمان عدم تأخر رحلتكم. نتعامل مع جميع خطوط الطيران.\n\nالخدمة متاحة على مدار الساعة لمواكبة مواعيد الرحلات المختلفة، مع دعم باللغات المتعددة.',
    fullDescriptionEn: 'Fast and efficient transit visa services available 24/7.',
    icon: 'Plane',
    category: 'VISAS',
    categoryAr: 'التأشيرات',
    price: 150,
    priceNote: 'يبدأ من',
    priceNoteEn: 'Starting from',
    duration: '1-2 أيام عمل',
    durationEn: '1-2 business days',
    features: ['إنجاز سريع خلال 24 ساعة', 'بدون حضور شخصي', 'متابعة إلكترونية كاملة', 'دعم متعدد اللغات', 'متاح 24/7'],
    featuresEn: ['Fast 24h processing', 'No personal attendance', 'Full electronic follow-up', 'Multi-language support', 'Available 24/7'],
    requirements: ['جواز سفر ساري المفعول', 'تذكرة الطيران للوجهة', 'تأشيرة الدخول للبلد النهائي'],
    requirementsEn: ['Valid passport', 'Flight ticket to destination', 'Entry visa for final destination'],
    steps: [
      { title: 'تقديم الطلب', description: 'أرسل طلبك مع المستندات عبر المنصة', icon: 'Upload' },
      { title: 'معالجة سريعة', description: 'نتعامل مع طلبك فوراً لضمان عدم تأخر رحلتك', icon: 'Zap' },
      { title: 'استلام التأشيرة', description: 'تصدر التأشيرة إلكترونياً وتُرسل لبريدك', icon: 'Mail' },
    ],
    stepsEn: [
      { title: 'Submit Request', description: 'Send request with documents via platform', icon: 'Upload' },
      { title: 'Fast Processing', description: 'Immediate handling to avoid travel delays', icon: 'Zap' },
      { title: 'Receive Visa', description: 'Visa issued electronically and emailed to you', icon: 'Mail' },
    ],
    faq: [
      { question: 'هل أحتاج تأشيرة عبور إذا كان انتظاري أقل من 12 ساعة؟', answer: 'قد لا تحتاجها إذا بقيت في المنطقة المحظورة بالمطار.' },
      { question: 'كم تستغرق إصدار تأشيرة العبور؟', answer: 'عادة من 24 إلى 48 ساعة عمل فقط.' },
    ],
    faqEn: [
      { question: 'Do I need a transit visa for under 12 hours?', answer: 'Not if staying in the airport restricted area.' },
      { question: 'How long does a transit visa take?', answer: 'Usually 24-48 business hours.' },
    ],
    requiredDocuments: ['جواز سفر ساري المفعول', 'تذكرة طيران مؤكد للوجهة التالية', 'تأشيرة الدخول للبلد النهائي'],
    requiredDocumentsEn: ['Valid passport', 'Confirmed flight ticket', 'Entry visa for final country'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#2580eb] via-[#60a5fa] to-[#93c5fd]',
  },
  {
    id: 'visa-residency',
    name: 'إقامة ومقيمين',
    nameEn: 'Residency Permit',
    description: 'خدمة استخراج وتجديد الإقامة للمقيمين في المملكة العربية السعودية عبر أبشر ووزارة الداخلية.',
    descriptionEn: 'Residency permit issuance and renewal through Absher and Ministry of Interior.',
    fullDescription: 'نقدم خدمة متكاملة لاستخراج وتجديد إقامة المقيمين من خلال المنصات الحكومية الرسمية. نتابع جميع الإجراءات عبر نظام أبشر ووزارة الداخلية بكفاءة وسرعة.\n\nفريقنا يضمن إنجاز إجراءات الإقامة في أسرع وقت، سواء الاستخراج الأولي أو التجديد أو التعديل. نتعامل مع جميع أنواع الإقامات.\n\nنقدم استشارة مجانية حول نوع الإقامة المناسب ومتطلباتها، ونتابع حتى الانتهاء الكامل.\n\nنلتزم بالمواعيد النهائية ونوفر تحديثات دورية حول حالة طلبكم.',
    fullDescriptionEn: 'Comprehensive residency services through official government platforms.',
    icon: 'Home',
    category: 'VISAS',
    categoryAr: 'التأشيرات',
    price: 350,
    priceNote: 'يبدأ من',
    priceNoteEn: 'Starting from',
    duration: '2-4 أيام عمل',
    durationEn: '2-4 business days',
    features: ['تجديد سريع وآمن', 'متابعة حالة المعاملة', 'تنسيق مع جهة العمل', 'إشعار عند الانتهاء', 'استشارة مجانية', 'جميع أنواع الإقامات'],
    featuresEn: ['Fast and safe renewal', 'Status tracking', 'Employer coordination', 'Completion notification', 'Free consultation', 'All residency types'],
    requirements: ['جواز سفر ساري المفعول', 'صورة الهوية الوطنية', 'عقد العمل الحالي', 'صور حديثة'],
    requirementsEn: ['Valid passport', 'National ID copy', 'Current work contract', 'Recent photos'],
    steps: [
      { title: 'استشارة أولية', description: 'نحدد نوع الإقامة ومتطلباتها', icon: 'MessageSquare' },
      { title: 'تجهيز المستندات', description: 'نجمع ونرتب المستندات المطلوبة', icon: 'FileText' },
      { title: 'تقديم المعاملة', description: 'نقدم عبر منصة أبشر أو الوزارة المختصة', icon: 'Monitor' },
      { title: 'المتابعة والإنجاز', description: 'نتابع حتى الانتهاء ونبلّغك بالنتيجة', icon: 'CheckCircle' },
    ],
    stepsEn: [
      { title: 'Consultation', description: 'Determine residency type and requirements', icon: 'MessageSquare' },
      { title: 'Prepare Documents', description: 'Collect and arrange required documents', icon: 'FileText' },
      { title: 'Submit Transaction', description: 'Submit via Absher or relevant ministry', icon: 'Monitor' },
      { title: 'Follow-up', description: 'Track until completion and notify you', icon: 'CheckCircle' },
    ],
    faq: [
      { question: 'هل يمكن تجديد الإقامة عبر الإنترنت؟', answer: 'نعم، عبر منصة أبشر في حال استيفاء الشروط. فريقنا يتابع بالكامل.' },
      { question: 'ما هي تكلفة التجديد؟', answer: 'تبدأ من 350 ر.س شاملة جميع الإجراءات.' },
      { question: 'كم تستغرق عملية التجديد؟', answer: 'عادة من 2 إلى 4 أيام عمل.' },
    ],
    faqEn: [
      { question: 'Can I renew online?', answer: 'Yes, through Absher if conditions are met.' },
      { question: 'What is the renewal cost?', answer: 'Starting from 350 SAR.' },
      { question: 'How long does renewal take?', answer: 'Usually 2-4 business days.' },
    ],
    requiredDocuments: ['جواز سفر ساري المفعول', 'هوية وطنية أو إقامة حالية', 'عقد العمل أو خطاب جهة العمل', 'صور شخصية حديثة', 'آخر كشف رواتب'],
    requiredDocumentsEn: ['Valid passport', 'Current ID or residency', 'Work contract or employer letter', 'Recent photos', 'Latest salary statement'],
    isPopular: true,
    isActive: true,
    gradient: 'from-[#2580eb] via-[#818cf8] to-[#a78bfa]',
  },
  {
    id: 'contract-work',
    name: 'تصديق عقود العمل',
    nameEn: 'Work Contract Attestation',
    description: 'تصديق وتوثيق عقود العمل رسمياً من الجهات المختصة لحماية حقوقك القانونية.',
    descriptionEn: 'Official attestation of work contracts to protect your legal rights.',
    fullDescription: 'نقدم خدمة تصديق وتوثيق عقود العمل بشكل رسمي وقانوني يضمن حماية حقوقك. نتعامل مع جميع أنواع العقود ونوفر استشارة قانونية شاملة قبل التصديق.\n\nفريقنا يراجع العقد بالكامل قبل التقديم لضمان عدم وجود ثغرات قانونية.\n\ننتولى جميع الإجراءات الرسمية من التصديق لدى الجهات المختصة ونوفر نسخاً إلكترونية وورقية.\n\nالخدمة تشمل استشارة قانونية مجانية حول بنود العقد وحقوقك وواجباتك.',
    fullDescriptionEn: 'Official work contract attestation with free legal consultation.',
    icon: 'FileText',
    category: 'CONTRACTS',
    categoryAr: 'العقود',
    price: 200,
    priceNote: 'يبدأ من',
    priceNoteEn: 'Starting from',
    duration: '1-2 أيام عمل',
    durationEn: '1-2 business days',
    features: ['تصديق رسمي معتمد', 'مراجعة العقد قبل التصديق', 'نسخ إلكترونية وورقية', 'استشارة قانونية مجانية', 'ضمان صحة البنود'],
    featuresEn: ['Official certified attestation', 'Contract review', 'Digital and paper copies', 'Free legal consultation', 'Terms validity guarantee'],
    requirements: ['العقد الأصلي للتوقيع', 'هوية صاحب العمل', 'هوية الموظف', 'رقم الإقامة'],
    requirementsEn: ['Original contract', 'Employer ID', 'Employee ID', 'Residency number'],
    steps: [
      { title: 'مراجعة العقد', description: 'نراجع العقد بالكامل للتأكد من سلامة البنود', icon: 'Search' },
      { title: 'التصديق الرسمي', description: 'نقدم للجهة المختصة للتصديق والتوثيق', icon: 'Stamp' },
      { title: 'تسليم النسخ', description: 'نسلم النسخ المصدقة لك وللطرف الآخر', icon: 'Package' },
    ],
    stepsEn: [
      { title: 'Review Contract', description: 'Complete review for clause accuracy', icon: 'Search' },
      { title: 'Official Attestation', description: 'Submit to competent authority', icon: 'Stamp' },
      { title: 'Deliver Copies', description: 'Deliver attested copies to both parties', icon: 'Package' },
    ],
    faq: [
      { question: 'هل يمكن تصديق تعديلات على عقود قائمة؟', answer: 'نعم، نقوم بتصديق العقود الجديدة والتعديلات على القائمة.' },
      { question: 'ما هي أتعاب التصديق؟', answer: 'تبدأ من 200 ر.س شاملة المراجعة والتصديق والنسخ.' },
    ],
    faqEn: [
      { question: 'Can you attest contract amendments?', answer: 'Yes, for new contracts and amendments.' },
      { question: 'What are the fees?', answer: 'Starting from 200 SAR including review, attestation, and copies.' },
    ],
    requiredDocuments: ['العقد الأصلي (3 نسخ)', 'سجل تجاري ساري للمؤسسة', 'هوية صاحب العمل أو ممثله', 'هوية الموظف أو إقامته'],
    requiredDocumentsEn: ['Original contract (3 copies)', 'Valid commercial registration', 'Employer or representative ID', 'Employee ID or residency'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#14b8a6] via-[#2dd4bf] to-[#5eead4]',
  },
  {
    id: 'contract-rental',
    name: 'عقود الإيجار',
    nameEn: 'Rental Contracts',
    description: 'إعداد عقود الإيجار المعتمدة من الوزارة مع تسجيلها في منصة عقار.',
    descriptionEn: 'Rental contract preparation approved by the Ministry, registered on Aqar platform.',
    fullDescription: 'نقدم خدمة إعداد عقود الإيجار المعتمدة رسمياً من وزارة الشؤون البلدية والقروية والسكنى وتسجيلها في منصة عقار. نضمن عقداً قانونياً صحيحاً يحمي حقوقك كمؤجر أو مستأجر.\n\nفريقنا يإعداد العقد وفقاً للصيغ المعتمدة مع مراعاة جميع الظروف الخاصة بكل عقد.\n\nالخدمة تشمل التسجيل في منصة عقار إلكترونياً مما يضمن صحته القانونية وسهولة الوصول إليه.\n\nنسعى دائماً لتجربة سلسة تحمي حقوق جميع الأطراف.',
    fullDescriptionEn: 'Official rental contracts with Aqar platform registration.',
    icon: 'FileSignature',
    category: 'CONTRACTS',
    categoryAr: 'العقود',
    price: 250,
    priceNote: 'يبدأ من',
    priceNoteEn: 'Starting from',
    duration: '1 يوم عمل',
    durationEn: '1 business day',
    features: ['صيغة معتمدة رسمياً', 'تسجيل في منصة عقار', 'نسخ متعددة للطرفين', 'استشارة قانونية شاملة', 'إنجاز خلال يوم'],
    featuresEn: ['Official approved format', 'Aqar registration', 'Multiple copies', 'Legal consultation', 'Completed in 1 day'],
    requirements: ['هوية المؤجر', 'هوية المستأجر', 'صك ملكية العقار', 'بيانات العقار الكاملة'],
    requirementsEn: ['Owner ID', 'Tenant ID', 'Property deed', 'Complete property details'],
    steps: [
      { title: 'جمع البيانات', description: 'نجمع بيانات العقار والأطراف المعنية', icon: 'ClipboardList' },
      { title: 'إعداد العقد', description: 'نعد العقد بالصيغة المعتمدة من الوزارة', icon: 'FileSignature' },
      { title: 'تسجيل في عقار', description: 'نسجل العقد في منصة عقار إلكترونياً', icon: 'Globe' },
      { title: 'تسليم النسخ', description: 'نسلم النسخ المطبوعة للطرفين', icon: 'Package' },
    ],
    stepsEn: [
      { title: 'Collect Data', description: 'Gather property and party information', icon: 'ClipboardList' },
      { title: 'Prepare Contract', description: 'Prepare in Ministry-approved format', icon: 'FileSignature' },
      { title: 'Register on Aqar', description: 'Register electronically on Aqar platform', icon: 'Globe' },
      { title: 'Deliver Copies', description: 'Deliver printed copies to both parties', icon: 'Package' },
    ],
    faq: [
      { question: 'هل يمكن تسجيل العقد بدون حضور المالك؟', answer: 'نعم، بتفويض رسمي من المالك مع المستندات المطلوبة.' },
      { question: 'هل العقد معتمد قانونياً؟', answer: 'نعم، معتمد من الوزارة ومسجل في منصة عقار.' },
    ],
    faqEn: [
      { question: 'Can I register without the owner present?', answer: 'Yes, with official power of attorney.' },
      { question: 'Is the contract legally valid?', answer: 'Yes, Ministry-approved and Aqar-registered.' },
    ],
    requiredDocuments: ['هوية المالك الأصلية', 'صك ملكية العقار أو استمارة 7001', 'هوية المستأجر', 'بيانات العقار (المساحة والدور)', 'اتفاقيات سابقة بين الأطراف'],
    requiredDocumentsEn: ['Owner original ID', 'Property deed or form 7001', 'Tenant ID', 'Property details', 'Previous agreements'],
    isPopular: true,
    isActive: true,
    gradient: 'from-[#14b8a6] via-[#06b6d4] to-[#22d3ee]',
  },
  {
    id: 'vehicle-transfer',
    name: 'نقل ملكية المركبات',
    nameEn: 'Vehicle Ownership Transfer',
    description: 'إنجاز إجراءات نقل ملكية المركبات بين الأفراد بسهولة وسرعة.',
    descriptionEn: 'Complete vehicle ownership transfer between individuals.',
    fullDescription: 'نقدم خدمة نقل ملكية المركبات بشكل متكامل يشمل جميع الإجراءات من الفحص الفني إلى تجديد التأمين واستخراج اللوحة الجديدة.\n\nفريقنا يتولى جميع الإجراءات نيابة عنك من متابعة الفحص الفني إلى التسجيل في المنصات الحكومية.\n\nالخدمة تشمل فحص المركبة وتجديد التأمين واستخراج اللوحة الجديدة وتوصيل الوثائق.\n\nنسعى لتقديم خدمة مريحة وموثوقة توفر وقتك وجهدك.',
    fullDescriptionEn: 'Complete door-to-door vehicle ownership transfer service.',
    icon: 'Car',
    category: 'VEHICLES',
    categoryAr: 'المركبات',
    price: 400,
    priceNote: 'يبدأ من',
    priceNoteEn: 'Starting from',
    duration: '1-2 أيام عمل',
    durationEn: '1-2 business days',
    features: ['إنجاز جميع الإجراءات', 'تجديد التأمين الكلي', 'استخراج لوحة جديدة', 'توصيل الوثائق', 'فحص فني معتمد', 'خدمة من الباب للباب'],
    featuresEn: ['Complete procedures', 'Insurance renewal', 'New plate issuance', 'Document delivery', 'Certified inspection', 'Door-to-door service'],
    requirements: ['هوية البائع والمشتري', 'شهادة فحص المركبة', 'عقد البيع الأصلي', 'سجل المركبة'],
    requirementsEn: ['Seller and buyer IDs', 'Inspection certificate', 'Sale contract', 'Vehicle registration'],
    steps: [
      { title: 'فحص المركبة', description: 'نرتب للفحص في المركز المعتمد الأقرب', icon: 'Car' },
      { title: 'إعداد المستندات', description: 'نجهز المستندات المطلوبة لعملية النقل', icon: 'FileText' },
      { title: 'التسجيل الرسمي', description: 'نسجل نقل الملكية في المنصة الحكومية', icon: 'Monitor' },
      { title: 'اللوحة والتأمين', description: 'نستخرج اللوحة الجديدة ونجدّد التأمين', icon: 'CreditCard' },
      { title: 'توصيل الوثائق', description: 'نوصّل الوثائق الجديدة للعنوان المحدد', icon: 'Truck' },
    ],
    stepsEn: [
      { title: 'Inspection', description: 'Arrange at nearest certified center', icon: 'Car' },
      { title: 'Prepare Documents', description: 'Prepare all transfer documents', icon: 'FileText' },
      { title: 'Registration', description: 'Register on government platform', icon: 'Monitor' },
      { title: 'Plate & Insurance', description: 'New plate and insurance renewal', icon: 'CreditCard' },
      { title: 'Deliver Documents', description: 'Deliver to specified address', icon: 'Truck' },
    ],
    faq: [
      { question: 'هل أحتاج لحضور شخصي؟', answer: 'لا، يتولى فريقنا الإجراءات. قد تحتاج حضور الفحص فقط.' },
      { question: 'ما هي التكلفة الشاملة؟', answer: 'تبدأ من 400 ر.س شاملة الفحص والتسجيل واللوحة والتأمين.' },
    ],
    faqEn: [
      { question: 'Do I need to be present?', answer: 'No, except optionally for inspection.' },
      { question: 'What is the total cost?', answer: 'Starting from 400 SAR including inspection, registration, plate, and insurance.' },
    ],
    requiredDocuments: ['هوية البائع الأصلية', 'هوية المشتري الأصلية', 'رخصة المركبة', 'شهادة الفحص الفني', 'عقد البيع موقّع من الطرفين'],
    requiredDocumentsEn: ['Seller original ID', 'Buyer original ID', 'Vehicle registration', 'Inspection certificate', 'Signed sale contract'],
    isPopular: true,
    isActive: true,
    gradient: 'from-[#7c3aed] via-[#8b5cf6] to-[#a78bfa]',
  },
  {
    id: 'vehicle-deregister',
    name: 'إسقاط المركبات',
    nameEn: 'Vehicle Deregistration',
    description: 'إنجاز إجراءات إسقاط المركبات من السجلات الرسمية وتجهيز المستندات اللازمة.',
    descriptionEn: 'Vehicle deregistration from official records.',
    fullDescription: 'نقدم خدمة إسقاط المركبات من السجلات الرسمية بشكل رسمي وسريع. سواء كنت تريد إسقاط مركبة قديمة أو تالفة أو غير مستخدمة.\n\nفريقنا يتابع جميع الإجراءات مع الجهات الحكومية المختصة ونضمن إتمام العملية بشكل قانوني وسليم.\n\nالخدمة تشمل إعداد المستندات والتقديم للجهات وإشعارك بالاكتمال مع تقرير مفصل.\n\nنسعى لتقديم خدمة سريعة تخلّصك من أعباء الإجراءات الحكومية.',
    fullDescriptionEn: 'Official vehicle deregistration handled efficiently.',
    icon: 'Car',
    category: 'VEHICLES',
    categoryAr: 'المركبات',
    price: 200,
    priceNote: 'يبدأ من',
    priceNoteEn: 'Starting from',
    duration: '1-3 أيام عمل',
    durationEn: '1-3 business days',
    features: ['إنجاز سريع', 'إشعار فوري بالاكتمال', 'تجهيز جميع المستندات', 'متابعة حتى الإغلاق', 'تقرير مفصل'],
    featuresEn: ['Fast processing', 'Instant completion notice', 'All documents prepared', 'Follow-up to closure', 'Detailed report'],
    requirements: ['هوية المالك الحالي', 'رخصة المركبة', 'لوحة المركبة', 'سبب الإسقاط'],
    requirementsEn: ['Current owner ID', 'Vehicle registration', 'Vehicle plate', 'Reason for deregistration'],
    steps: [
      { title: 'تقديم الطلب', description: 'نجمع المستندات ونعد طلب الإسقاط', icon: 'FileText' },
      { title: 'تقديم للجهة', description: 'نقدم للجهة الحكومية المختصة', icon: 'Send' },
      { title: 'متابعة الإنجاز', description: 'نتابع حتى الإشعار بالاكتمال', icon: 'CheckCircle' },
    ],
    stepsEn: [
      { title: 'Submit Request', description: 'Prepare documents and deregistration request', icon: 'FileText' },
      { title: 'Submit to Authority', description: 'Submit to relevant government authority', icon: 'Send' },
      { title: 'Track Completion', description: 'Follow up until completion notice', icon: 'CheckCircle' },
    ],
    faq: [
      { question: 'كم يستغرق إسقاط المركبة؟', answer: 'عادة من 1 إلى 3 أيام عمل.' },
      { question: 'ما هي المستندات المطلوبة؟', answer: 'هوية المالك ورخصة المركبة ولوحتها وسبب الإسقاط.' },
    ],
    faqEn: [
      { question: 'How long does deregistration take?', answer: 'Usually 1-3 business days.' },
      { question: 'What documents are needed?', answer: 'Owner ID, registration, plate, and reason for deregistration.' },
    ],
    requiredDocuments: ['هوية المالك الأصلية', 'رخصة المركبة الأصلية', 'لوحة المركبة', 'خطاب أو سبب الإسقاط'],
    requiredDocumentsEn: ['Owner original ID', 'Vehicle registration', 'Vehicle plate', 'Deregistration reason letter'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#7c3aed] via-[#c084fc] to-[#e879f9]',
  },
  {
    id: 'violations-payment',
    name: 'تجاوز المخالفات',
    nameEn: 'Traffic Violations',
    description: 'متابعة وسداد المخالفات المرورية والحكومية عبر الأنظمة الرسمية مع تقديم تفاصيل المخالفات.',
    descriptionEn: 'Follow-up and payment of traffic and government violations through official systems.',
    fullDescription: 'نقدم خدمة متابعة وسداد المخالفات المرورية والحكومية عبر الأنظمة الرسمية. نوفر تفاصيل شاملة عن كل مخالفة مع إمكانية السداد الفوري.\n\nفريقنا يتتبع جميع المخالفات المسجلة على اسمك أو مركبتك ويقدم تقريراً مفصلاً.\n\nالخدمة تشمل مراجعة المخالفات والتأكد من صحتها وسدادها عبر الأنظمة الحكومية المعتمدة.\n\nنسعى لتسهيل عملية السداد وتوفير رؤية واضحة لجميع المخالفات المعلقة.',
    fullDescriptionEn: 'Track and pay traffic violations through official systems with detailed reports.',
    icon: 'Shield',
    category: 'VEHICLES',
    categoryAr: 'المركبات',
    price: 100,
    priceNote: 'رسوم الخدمة',
    priceNoteEn: 'Service fee',
    duration: 'فوري',
    durationEn: 'Instant',
    features: ['سداد فوري للمخالفات', 'عرض تفاصيل المخالفة', 'إيصال دفع إلكتروني', 'متابعة المخالفات المستمرة', 'تقرير شامل'],
    featuresEn: ['Instant violation payment', 'Detailed violation view', 'Electronic payment receipt', 'Continuous tracking', 'Comprehensive report'],
    requirements: ['رقم الهوية الوطنية', 'رقم المركبة (رقم اللوحة)', 'رقم رخصة القيادة'],
    requirementsEn: ['National ID number', 'Vehicle plate number', 'Driving license number'],
    steps: [
      { title: 'استعلام المخالفات', description: 'نبحث عن جميع المخالفات المسجلة على اسمك', icon: 'Search' },
      { title: 'عرض التفاصيل', description: 'نعرض تفاصيل كل مخالفة مع المبلغ المستحق', icon: 'List' },
      { title: 'السداد الفوري', description: 'نسدد المخالفات عبر الأنظمة الحكومية المعتمدة', icon: 'CreditCard' },
      { title: 'إيصال الدفع', description: 'نسلم إيصال الدفع الإلكتروني لكل مخالفة', icon: 'CheckCircle' },
    ],
    stepsEn: [
      { title: 'Query Violations', description: 'Search all violations registered to you', icon: 'Search' },
      { title: 'View Details', description: 'Show each violation with due amount', icon: 'List' },
      { title: 'Instant Payment', description: 'Pay through certified government systems', icon: 'CreditCard' },
      { title: 'Payment Receipt', description: 'Electronic receipt for each violation', icon: 'CheckCircle' },
    ],
    faq: [
      { question: 'هل يمكن السداد عبر الهاتف؟', answer: 'نعم، ننجز السداد إلكترونياً عبر الأنظمة الحكومية المعتمدة.' },
      { question: 'كم تبلغ رسوم الخدمة؟', answer: 'رسوم الخدمة 100 ر.س بالإضافة لمبلغ المخالفات.' },
      { question: 'هل أستطيع معرفة المخالفات القديمة؟', answer: 'نعم، نستعلم عن جميع المخالفات المسجلة بغض النظر عن تاريخها.' },
    ],
    faqEn: [
      { question: 'Can I pay via phone?', answer: 'Yes, through certified government systems.' },
      { question: 'What is the service fee?', answer: '100 SAR plus the violation amount.' },
      { question: 'Can I check old violations?', answer: 'Yes, all registered violations regardless of date.' },
    ],
    requiredDocuments: ['رقم الهوية الوطنية', 'رقم المركبة (اللوحة)', 'رقم رخصة القيادة'],
    requiredDocumentsEn: ['National ID number', 'Vehicle plate number', 'Driving license number'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#ef4444] via-[#f97316] to-[#f59e0b]',
  },
  {
    id: 'travel-booking',
    name: 'إدارة وإنجاز حجوزات السفر',
    nameEn: 'Travel Booking Management',
    description: 'حجز وتأكيد تذاكر السفر والرحلات الداخلية والخارجية بأفضل الأسعار.',
    descriptionEn: 'Book and confirm travel tickets at the best prices.',
    fullDescription: 'نقدم خدمة حجز وتأكيد تذاكر السفر والرحلات الداخلية والخارجية بأفضل الأسعار المتاحة في السوق. نبحث عن أفضل العروض وننسّق جميع التفاصيل لرحلتك.\n\nفريقنا المختص يتعامل مع شركات الطيران والموزعين لضمان حصولك على أفضل سعر وأفضل شروط.\n\nالخدمة تشمل حجز التذاكر وترتيب الفنادق والنقل من وإلى المطار مع تأمين السفر الشامل.\n\nنسعى لتجربة سفر مريحة وسلسة من لحظة الحجز وحتى الوصول.',
    fullDescriptionEn: 'Best-price travel booking with full trip coordination.',
    icon: 'Plane',
    category: 'TRAVEL',
    categoryAr: 'السفر',
    price: 500,
    priceNote: 'رسوم الخدمة',
    priceNoteEn: 'Service fee',
    duration: '1-2 أيام عمل',
    durationEn: '1-2 business days',
    features: ['بحث عن أرخص الأسعار', 'رحلات دولية ومحلية', 'ترتيب الفنادق والنقل', 'تأمين السفر شامل', 'مرافقة الحجز', 'تعديل وإلغاء سهل'],
    featuresEn: ['Best price search', 'International and domestic', 'Hotel and transport arrangement', 'Travel insurance', 'Booking assistance', 'Easy modification'],
    requirements: ['جواز سفر ساري المفعول', 'التواريخ المطلوبة للسفر', 'عدد المسافرين', 'الميزانية المتوقعة'],
    requirementsEn: ['Valid passport', 'Travel dates', 'Number of travelers', 'Expected budget'],
    steps: [
      { title: 'استشارة السفر', description: 'نحدد احتياجاتك وتفضيلاتك للرحلة', icon: 'MessageSquare' },
      { title: 'البحث عن أفضل العروض', description: 'نبحث في شركات الطيران والموزعين لأفضل الأسعار', icon: 'Search' },
      { title: 'تأكيد الحجز', description: 'نؤكد الحجز ونرسل لك التفاصيل الكاملة', icon: 'CheckCircle' },
      { title: 'التجهيز النهائي', description: 'نرتب الفنادق والنقل وتأمين السفر', icon: 'Package' },
    ],
    stepsEn: [
      { title: 'Travel Consultation', description: 'Identify your trip needs and preferences', icon: 'MessageSquare' },
      { title: 'Best Deals Search', description: 'Search airlines and distributors for best prices', icon: 'Search' },
      { title: 'Confirm Booking', description: 'Confirm and send you full details', icon: 'CheckCircle' },
      { title: 'Final Preparation', description: 'Arrange hotels, transport, and insurance', icon: 'Package' },
    ],
    faq: [
      { question: 'هل يمكن حجز رحلات متعددة؟', answer: 'نعم، نحجز رحلات متعددة وننسّق بينها لتوفير أفضل سعر.' },
      { question: 'هل تشمل الخدمة التأمين؟', answer: 'نعم، يمكن إضافة تأمين السفر الشامل كجزء من الخدمة.' },
      { question: 'كيف أحصل على أفضل سعر؟', answer: 'فريقنا يبحث في شركات الطيران والموزعين للحصول على أفضل عرض.' },
    ],
    faqEn: [
      { question: 'Can I book multiple flights?', answer: 'Yes, we coordinate multi-flight bookings for best prices.' },
      { question: 'Does the service include insurance?', answer: 'Yes, comprehensive travel insurance can be added.' },
      { question: 'How do I get the best price?', answer: 'Our team searches airlines and distributors for the best deal.' },
    ],
    requiredDocuments: ['جواز سفر ساري المفعول', 'التواريخ المطلوبة', 'عدد المسافرين', 'الميزانية المتوقعة', 'تفضيلات السفر'],
    requiredDocumentsEn: ['Valid passport', 'Required dates', 'Number of travelers', 'Expected budget', 'Travel preferences'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#f59e0b] via-[#f97316] to-[#ef4444]',
  },
  {
    id: 'hotel-booking',
    name: 'حجز الفنادق',
    nameEn: 'Hotel Booking',
    description: 'حجز أفضل الفنادق والإقامات بأسعار تنافسية مع ترتيب جميع التفاصيل.',
    descriptionEn: 'Book the best hotels at competitive prices with all logistics arranged.',
    fullDescription: 'نقدم خدمة حجز أفضل الفنادق والإقامات بأسعار تنافسية في جميع المدن والمواقع السياحية. نتعامل مع فنادق عالمية ومحلية لضمان خيارات متنوعة تناسب ميزانيتك.\n\nفريقنا ينسّق جميع تفاصيل الإقامة من الحجز إلى تسجيل الدخول والخروج مع ترتيب أي خدمات إضافية تحتاجها.\n\nالخدمة تشمل مقارنة الأسعار بين الفنادق المختلفة واختيار الأنسب من حيث الموقع والجودة والسعر.\n\nنسعى لتجربة إقامة مريحة تتجاوز توقعاتك.',
    fullDescriptionEn: 'Competitive hotel booking with full logistics arrangement.',
    icon: 'Hotel',
    category: 'TRAVEL',
    categoryAr: 'السفر',
    price: 300,
    priceNote: 'رسوم الخدمة',
    priceNoteEn: 'Service fee',
    duration: 'فوري',
    durationEn: 'Instant',
    features: ['أسعار تنافسية جداً', 'فنادق معتمدة ومتنوعة', 'خيارات دفع مريحة', 'إلغاء مرنة', 'مقارنة شاملة للأسعار', 'دعم على مدار الساعة'],
    featuresEn: ['Very competitive prices', 'Certified diverse hotels', 'Flexible payment', 'Flexible cancellation', 'Comprehensive price comparison', '24/7 support'],
    requirements: ['تواريخ الإقامة المطلوبة', 'عدد الغرف والضيوف', 'المدينة المطلوبة', 'نوع الفندق المفضل'],
    requirementsEn: ['Required stay dates', 'Number of rooms and guests', 'Desired city', 'Preferred hotel type'],
    steps: [
      { title: 'تحديد الاحتياجات', description: 'نحدد معايير الإقامة والميزانية', icon: 'ClipboardList' },
      { title: 'مقارنة الأسعار', description: 'نقارن الأسعار بين الفنادق المتاحة', icon: 'Search' },
      { title: 'تأكيد الحجز', description: 'نؤكد الحجز ونرسل لك التفاصيل', icon: 'CheckCircle' },
      { title: 'الدعم المستمر', description: 'ندعمك أثناء الإقامة لأي طلبات', icon: 'Headphones' },
    ],
    stepsEn: [
      { title: 'Identify Needs', description: 'Determine accommodation criteria and budget', icon: 'ClipboardList' },
      { title: 'Compare Prices', description: 'Compare prices across available hotels', icon: 'Search' },
      { title: 'Confirm Booking', description: 'Confirm and send you details', icon: 'CheckCircle' },
      { title: 'Ongoing Support', description: 'Support during your stay for any needs', icon: 'Headphones' },
    ],
    faq: [
      { question: 'هل يمكن تعديل الحجز؟', answer: 'نعم، نوفر خيارات تعديل وإلغاء مرنة حسب سياسة الفندق.' },
      { question: 'ما هي أنواع الفنادق المتاحة؟', answer: 'نوفر خيارات من الفنادق الاقتصادية إلى الفنادق الفاخرة.' },
    ],
    faqEn: [
      { question: 'Can I modify my booking?', answer: 'Yes, flexible modification and cancellation options.' },
      { question: 'What hotel types are available?', answer: 'From budget to luxury hotels.' },
    ],
    requiredDocuments: ['تواريخ الإقامة المطلوبة', 'عدد الغرف والضيوف', 'المدينة أو المنطقة المطلوبة', 'الميزانية المتوقعة'],
    requiredDocumentsEn: ['Required stay dates', 'Room and guest count', 'Desired city or area', 'Expected budget'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#f59e0b] via-[#eab308] to-[#facc15]',
  },
  {
    id: 'business-services',
    name: 'خدمات قطاع الأعمال',
    nameEn: 'Business Services',
    description: 'خدمات متكاملة لتأسيس وإدارة الشركات والأعمال من سجل تجاري إلى التراخيص اللازمة.',
    descriptionEn: 'Comprehensive company establishment and management services.',
    fullDescription: 'نقدم خدمات متكاملة لتأسيس الشركات والأعمال تشمل استخراج السجل التجاري والحصول على التراخيص اللازمة وإعداد النظام الداخلي.\n\nفريقنا من المتخصصين في القانون التجاري يرافقك في جميع مراحل التأسيس من اختيار الهيكل القانوني إلى التسجيل النهائي.\n\nالخدمة تشمل الاستشارة الأولية المجانية وتجهيز جميع المستندات والتقديم للجهات الحكومية المختصة.\n\nنسعى لتسهيل إجراءات تأسيس أعمالك وتمكينك من التركيز على نمو أعمالك.',
    fullDescriptionEn: 'End-to-end business setup from commercial registration to licenses.',
    icon: 'Building',
    category: 'BUSINESS',
    categoryAr: 'قطاع الأعمال',
    price: 1000,
    priceNote: 'يبدأ من',
    priceNoteEn: 'Starting from',
    duration: '5-7 أيام عمل',
    durationEn: '5-7 business days',
    features: ['تأسيس شركات متكامل', 'استخراج السجل التجاري', 'الحصول على التراخيص', 'استشارة أعمال شاملة', 'إعداد النظام الداخلي', 'مرافقة مستمرة'],
    featuresEn: ['Complete company setup', 'Commercial registration', 'License acquisition', 'Business consulting', 'Bylaws preparation', 'Continuous support'],
    requirements: ['أسماء الشركاء', 'رأس المال المتوقع', 'نوع النشاط التجاري', 'المكان المطلوب للشركة'],
    requirementsEn: ['Partner names', 'Expected capital', 'Business type', 'Desired company location'],
    steps: [
      { title: 'استشارة تأسيسية', description: 'نحدد الهيكل القانوني المناسب لأنشطتك', icon: 'MessageSquare' },
      { title: 'تجهيز المستندات', description: 'نعد جميع المستندات التأسيسية المطلوبة', icon: 'FileText' },
      { title: 'التسجيل والترخيص', description: 'نقدم للجهات الحكومية للتسجيل والحصول على التراخيص', icon: 'Send' },
      { title: 'الإنجاز والتسليم', description: 'نسلم جميع الوثائق والسجل التجاري الجاهز', icon: 'Package' },
      { title: 'المرافقة المستمرة', description: 'نرافقك في أي تعديلات أو تراخيص إضافية لاحقاً', icon: 'Headphones' },
    ],
    stepsEn: [
      { title: 'Foundation Consultation', description: 'Determine the right legal structure', icon: 'MessageSquare' },
      { title: 'Prepare Documents', description: 'Prepare all incorporation documents', icon: 'FileText' },
      { title: 'Register & License', description: 'Submit for registration and licenses', icon: 'Send' },
      { title: 'Completion', description: 'Deliver all documents and registration', icon: 'Package' },
      { title: 'Ongoing Support', description: 'Support for future modifications or licenses', icon: 'Headphones' },
    ],
    faq: [
      { question: 'كم يستغرق تأسيس شركة؟', answer: 'عادة من 5 إلى 7 أيام عمل حسب نوع الشركة والنشاط.' },
      { question: 'ما هي التراخيص المطلوبة؟', answer: 'تعتمد على نوع النشاط، ونحدد ذلك في الاستشارة الأولية.' },
      { question: 'هل تقدمون استشارة مجانية؟', answer: 'نعم، الاستشارة الأولية مجانية لتحديد متطلبات تأسيس شركتك.' },
    ],
    faqEn: [
      { question: 'How long does company setup take?', answer: 'Usually 5-7 business days depending on type.' },
      { question: 'What licenses are required?', answer: 'Depends on activity, determined in initial consultation.' },
      { question: 'Is consultation free?', answer: 'Yes, initial consultation is free.' },
    ],
    requiredDocuments: ['أسماء الشركاء والمعلومات الشخصية', 'رأس المال المتوقع', 'نوع النشاط التجاري', 'المكان المطلوب للشركة', 'أي تراخيص سابقة إن وجدت'],
    requiredDocumentsEn: ['Partner names and personal info', 'Expected capital', 'Business type', 'Desired location', 'Previous licenses if any'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#10b981] via-[#059669] to-[#047857]',
  },
  {
    id: 'government-services',
    name: 'الخدمات الحكومية',
    nameEn: 'Government Services',
    description: 'إنجاز جميع المعاملات الحكومية والرسمية بفعالية عبر منصات أبشر ومقيم والأنظمة الحكومية.',
    descriptionEn: 'Complete all government transactions efficiently through Absher and Muqeem.',
    fullDescription: 'نقدم خدمة إنجاز المعاملات الحكومية والرسمية عبر منصات أبشر ومقيم والأنظمة الحكومية الأخرى بكفاءة وسرعة. نتعامل مع جميع أنواع المعاملات الحكومية.\n\nفريقنا المختص يتابع جميع الإجراءات عبر الأنظمة الحكومية المعتمدة ويضمن إنجاز المعاملة في أسرع وقت.\n\nالخدمة تشمل استشارة مجانية لتحديد المعاملة المطلوبة والمستندات اللازمة، ثم متابعة المعاملة حتى الانتهاء.\n\nنسعى لتسهيل التعامل مع الجهات الحكومية وتوفير تجربة سلسة وخالية من التعقيدات.',
    fullDescriptionEn: 'Efficient government transaction handling through Absher and Muqeem.',
    icon: 'Shield',
    category: 'GOVERNMENT',
    categoryAr: 'الخدمات الحكومية',
    price: 200,
    priceNote: 'رسوم الخدمة',
    priceNoteEn: 'Service fee',
    duration: '2-5 أيام عمل',
    durationEn: '2-5 business days',
    features: ['خدمة أبشر شاملة', 'خدمة مقيم للمقيمين', 'متابعة المعاملات', 'إنجاز سريع وموثوق', 'استشارة مجانية', 'جميع أنواع المعاملات'],
    featuresEn: ['Comprehensive Absher', 'Muqeem for residents', 'Transaction tracking', 'Fast and reliable', 'Free consultation', 'All transaction types'],
    requirements: ['الهوية الوطنية أو الإقامة', 'رقم جوال مسجل في أبشر', 'البيانات المطلوبة حسب المعاملة'],
    requirementsEn: ['National ID or residency', 'Mobile number registered on Absher', 'Data required per transaction'],
    steps: [
      { title: 'تحديد المعاملة', description: 'نحدد نوع المعاملة ومتطلباتها بدقة', icon: 'Search' },
      { title: 'جمع المستندات', description: 'نجمع المستندات والبيانات المطلوبة', icon: 'FileText' },
      { title: 'التنفيذ عبر أبشر', description: 'ننجز المعاملة عبر المنصة الحكومية المعتمدة', icon: 'Monitor' },
      { title: 'الإنجاز والتسليم', description: 'نبلّغك بالإنجاز ونسلّم النتيجة', icon: 'CheckCircle' },
    ],
    stepsEn: [
      { title: 'Identify Transaction', description: 'Determine exact transaction type and requirements', icon: 'Search' },
      { title: 'Collect Documents', description: 'Gather required documents and data', icon: 'FileText' },
      { title: 'Execute via Absher', description: 'Process through certified government platform', icon: 'Monitor' },
      { title: 'Complete & Deliver', description: 'Notify completion and deliver result', icon: 'CheckCircle' },
    ],
    faq: [
      { question: 'ما هي المعاملات التي تنجزونها؟', answer: 'ننجز جميع المعاملات الحكومية المتاحة عبر أبشر ومقيم والأنظمة الحكومية الأخرى.' },
      { question: 'هل أحتاج لحضور شخصي؟', answer: 'في معظم الحالات لا حاجة للحضور، ننجز المعاملة إلكترونياً.' },
      { question: 'كم تبلغ رسوم الخدمة؟', answer: 'رسوم الخدمة 200 ر.س بالإضافة للرسوم الحكومية إن وجدت.' },
    ],
    faqEn: [
      { question: 'What transactions do you handle?', answer: 'All government transactions via Absher, Muqeem, and other platforms.' },
      { question: 'Do I need to attend personally?', answer: 'In most cases, no. We process electronically.' },
      { question: 'What is the service fee?', answer: '200 SAR plus government fees if applicable.' },
    ],
    requiredDocuments: ['الهوية الوطنية أو الإقامة السارية', 'رقم جوال مسجل في منصة أبشر', 'البيانات المطلوبة حسب نوع المعاملة'],
    requiredDocumentsEn: ['Valid national ID or residency', 'Mobile registered on Absher', 'Data required per transaction type'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#ef4444] via-[#dc2626] to-[#b91c1c]',
  },
  {
    id: 'electronic-services',
    name: 'الخدمات الإلكترونية',
    nameEn: 'Electronic Services',
    description: 'خدمات رقمية متقدمة للتحويل والتكامل الإلكتروني مع الأنظمة الحكومية والخاصة.',
    descriptionEn: 'Advanced digital services for electronic integration with government and private systems.',
    fullDescription: 'نقدم خدمات رقمية متقدمة للتحويل والتكامل الإلكتروني مع الأنظمة الحكومية والخاصة. نساعدك في رقامة أعمالك وتبسيط العمليات الإدارية.\n\nفريقنا من المتخصصين في التحول الرقمي يوفر حلولاً تقنية متقدمة تناسب احتياجات شركتك.\n\nالخدمة تشمل تحليل الاحتياجات الرقمية وتقديم الحلول المناسبة مع الدعم الفني المستمر.\n\nنسعى لتمكينك من الاستفادة من التقنيات الحديثة لتحسين كفاءة أعمالك.',
    fullDescriptionEn: 'Advanced digital transformation and system integration solutions.',
    icon: 'Laptop',
    category: 'ELECTRONIC',
    categoryAr: 'الخدمات الإلكترونية',
    price: 150,
    priceNote: 'رسوم الخدمة',
    priceNoteEn: 'Service fee',
    duration: 'فوري',
    durationEn: 'Instant',
    features: ['خدمات رقمية متقدمة', 'تكامل مع الأنظمة الحكومية', 'أمان عالي جداً', 'دعم فني متواصل', 'حلول مخصصة', 'استشارة تقنية مجانية'],
    featuresEn: ['Advanced digital services', 'Government system integration', 'High security', 'Continuous tech support', 'Custom solutions', 'Free tech consultation'],
    requirements: ['البيانات الأساسية للمستخدم', 'النظام الإلكتروني المطلوب التكامل معه'],
    requirementsEn: ['Basic user data', 'Target system for integration'],
    steps: [
      { title: 'تحليل الاحتياجات', description: 'نحلل احتياجاتك الرقمية ونقترح الحلول المناسبة', icon: 'Search' },
      { title: 'تصميم الحل', description: 'نصمم الحل الرقمي المخصص لاحتياجاتك', icon: 'Settings' },
      { title: 'التنفيذ والتكامل', description: 'ننفذ الحل ونكامله مع الأنظمة المطلوبة', icon: 'Monitor' },
      { title: 'الدعم والصيانة', description: 'نقدم دعماً فنياً مستمراً بعد التنفيذ', icon: 'Headphones' },
    ],
    stepsEn: [
      { title: 'Analyze Needs', description: 'Analyze digital needs and suggest solutions', icon: 'Search' },
      { title: 'Design Solution', description: 'Design custom digital solution', icon: 'Settings' },
      { title: 'Implement & Integrate', description: 'Execute and integrate with target systems', icon: 'Monitor' },
      { title: 'Support & Maintain', description: 'Provide ongoing technical support', icon: 'Headphones' },
    ],
    faq: [
      { question: 'ما هي الخدمات الإلكترونية المتاحة؟', answer: 'نقدم تكامل الأنظمة والحلول الرقمية المخصصة والتحول الرقمي الشامل.' },
      { question: 'هل تقدمون ضماناً تقنياً؟', answer: 'نعم، نقدم ضماناً تقنياً ودعماً فنياً مستمراً.' },
    ],
    faqEn: [
      { question: 'What electronic services are available?', answer: 'System integration, custom digital solutions, and comprehensive digital transformation.' },
      { question: 'Do you offer technical guarantee?', answer: 'Yes, with ongoing technical support.' },
    ],
    requiredDocuments: ['البيانات الأساسية للمستخدم أو الشركة', 'وصف النظام المطلوب التكامل معه', 'المتطلبات التقنية الخاصة'],
    requiredDocumentsEn: ['Basic user or company data', 'Target system description', 'Technical requirements'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#3b82f6] via-[#6366f1] to-[#8b5cf6]',
  },
  {
    id: 'university-jordan',
    name: 'التسجيل بالجامعات الأردنية',
    nameEn: 'Jordanian University Enrollment',
    description: 'المساعدة في التسجيل والتقديم على الجامعات الأردنية مع متابعة المعاملات اللازمة.',
    descriptionEn: 'Assistance with registration and application to Jordanian universities.',
    fullDescription: 'نقدم خدمة متكاملة للتسجيل والتقديم على الجامعات الأردنية. نساعدك في اختيار الجامعة والتخصص المناسب وتجهيز جميع المستندات المطلوبة.\n\nفريقنا المختص يتعامل مباشرة مع مكاتب القبول في الجامعات الأردنية لضمان معالجة طلبك بكفاءة.\n\nالخدمة تشمل الاستشارة الأكاديمية وتجهيز المستندات والتقديم إلكترونياً ومتابعة حتى الحصول على القبول.\n\nنسعى لتسهيل رحلتك الأكاديمية وتحقيق طموحاتك التعليمية.',
    fullDescriptionEn: 'Complete university enrollment assistance for Jordanian institutions.',
    icon: 'GraduationCap',
    category: 'UNIVERSITIES',
    categoryAr: 'التسجيل بالجامعات',
    price: 800,
    priceNote: 'رسوم الخدمة',
    priceNoteEn: 'Service fee',
    duration: '7-14 يوم',
    durationEn: '7-14 days',
    features: ['استشارة اختيار الجامعة', 'تجهيز المستندات المطلوبة', 'تقديم الطلب إلكترونياً', 'متابعة حتى القبول', 'ترجمة المستندات', 'مرافقة الأكاديمية'],
    featuresEn: ['University selection consultation', 'Document preparation', 'Electronic application', 'Follow-up to admission', 'Document translation', 'Academic mentoring'],
    requirements: ['الشهادات الدراسية المعتمدة', 'جواز السفر ساري المفعول', 'صور شخصية', 'رسوم التقديم'],
    requirementsEn: ['Certified academic certificates', 'Valid passport', 'Photos', 'Application fees'],
    steps: [
      { title: 'الاستشارة الأكاديمية', description: 'نحلل ملفك الأكاديمي ونقترح الجامعات والتخصصات المناسبة', icon: 'GraduationCap' },
      { title: 'تجهيز المستندات', description: 'نجهز جميع المستندات المطلوبة مع الترجمة والتصديق', icon: 'FileText' },
      { title: 'تقديم الطلب', description: 'نقدم طلبك إلكترونياً أو مباشرة للجامعة', icon: 'Send' },
      { title: 'متابعة القبول', description: 'نتابع حالة الطلب حتى صدور قرار القبول', icon: 'CheckCircle' },
      { title: 'الإنجاز النهائي', description: 'نساعدك في إجراءات التسجيل النهائي والتأشيرة', icon: 'Package' },
    ],
    stepsEn: [
      { title: 'Academic Consultation', description: 'Analyze your profile and suggest universities', icon: 'GraduationCap' },
      { title: 'Prepare Documents', description: 'Prepare all required documents with translation', icon: 'FileText' },
      { title: 'Submit Application', description: 'Submit electronically or directly to university', icon: 'Send' },
      { title: 'Track Admission', description: 'Follow up until admission decision', icon: 'CheckCircle' },
      { title: 'Finalize', description: 'Help with final registration and visa', icon: 'Package' },
    ],
    faq: [
      { question: 'هل تساعدون في اختيار الجامعة؟', answer: 'نعم، نقدم استشارة أكاديمية شاملة لاختيار الجامعة والتخصص الأنسب.' },
      { question: 'ما هي الجامعات الأردنية المتاحة؟', answer: 'نعمل مع جميع الجامعات الأردنية المعتمدة both الخاصة والحكومية.' },
      { question: 'كم يستغرق الإجراء؟', answer: 'عادة من 7 إلى 14 يوماً حسب الجامعة والتخصص.' },
    ],
    faqEn: [
      { question: 'Do you help choose a university?', answer: 'Yes, comprehensive academic consultation for university and major selection.' },
      { question: 'Which Jordanian universities are available?', answer: 'We work with all accredited Jordanian universities.' },
      { question: 'How long does the process take?', answer: 'Usually 7-14 days depending on university and major.' },
    ],
    requiredDocuments: ['الشهادات الدراسية المعتمدة (الثانوية والجامعية)', 'جواز سفر ساري المفعول', 'صور شخصية حديثة', 'رسوم التقديم', 'ترجمة معتمدة للشهادات'],
    requiredDocumentsEn: ['Certified academic certificates (high school and university)', 'Valid passport', 'Recent photos', 'Application fees', 'Certified certificate translations'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#8b5cf6] via-[#7c3aed] to-[#6d28d9]',
  },
  {
    id: 'university-egypt',
    name: 'التسجيل بالجامعات المصرية',
    nameEn: 'Egyptian University Enrollment',
    description: 'المساعدة في التسجيل والتقديم على الجامعات المصرية مع التنسيق الكامل مع البعثات.',
    descriptionEn: 'Assistance with Egyptian university registration with embassy coordination.',
    fullDescription: 'نقدم خدمة متكاملة للتسجيل والتقديم على الجامعات المصرية مع التنسيق الكامل مع البعثات الدبلوماسية. نساعدك في اختيار الجامعة والتخصص المناسب.\n\nفريقنا المختص يتعامل مع الجامعات المصرية والبعثات لضمان معالجة طلبك بشكل سليم وسريع.\n\nالخدمة تشمل الاستشارة الأكاديمية وتجهيز المستندات والتقديم والتنسيق مع البعثة المصرية.\n\nنسعى لتحقيق طموحاتك الأكاديمية في أفضل الجامعات المصرية.',
    fullDescriptionEn: 'Complete Egyptian university enrollment with embassy coordination.',
    icon: 'GraduationCap',
    category: 'UNIVERSITIES',
    categoryAr: 'التسجيل بالجامعات',
    price: 800,
    priceNote: 'رسوم الخدمة',
    priceNoteEn: 'Service fee',
    duration: '7-14 يوم',
    durationEn: '7-14 days',
    features: ['تنسيق مع البعثات المصرية', 'تجهيز جميع المستندات', 'تقديم طلب الالتحاق', 'متابعة النتيجة', 'ترجمة المعادلة', 'مرافقة كاملة'],
    featuresEn: ['Embassy coordination', 'All documents prepared', 'Application submission', 'Result tracking', 'Credential evaluation', 'Full support'],
    requirements: ['الشهادات الدراسية المعتمدة', 'جواز السفر ساري المفعول', 'صور شخصية', 'إثبات الحساب البنكي'],
    requirementsEn: ['Certified academic certificates', 'Valid passport', 'Photos', 'Bank account proof'],
    steps: [
      { title: 'الاستشارة الأولية', description: 'نحدد الجامعة والتخصص المناسب لمؤهلاتك', icon: 'GraduationCap' },
      { title: 'تجهيز المستندات', description: 'نعد المستندات مع الترجمة والتصديق للمعادلة', icon: 'FileText' },
      { title: 'التنسيق مع البعثة', description: 'نتواصل مع البعثة المصرية لتطبيع المستندات', icon: 'Send' },
      { title: 'تقديم الطلب', description: 'نقدم طلبك للجامعة المصرية المعنية', icon: 'Monitor' },
      { title: 'متابعة القبول', description: 'نتابع حتى صدور قرار القبول والتسجيل', icon: 'CheckCircle' },
    ],
    stepsEn: [
      { title: 'Initial Consultation', description: 'Determine suitable university and major', icon: 'GraduationCap' },
      { title: 'Prepare Documents', description: 'Prepare documents with translation and attestation', icon: 'FileText' },
      { title: 'Embassy Coordination', description: 'Coordinate with Egyptian embassy for attestation', icon: 'Send' },
      { title: 'Submit Application', description: 'Submit to the relevant Egyptian university', icon: 'Monitor' },
      { title: 'Track Admission', description: 'Follow up until admission and registration', icon: 'CheckCircle' },
    ],
    faq: [
      { question: 'هل تتعاملون مع جميع الجامعات المصرية؟', answer: 'نعم، نتعامل مع الجامعات الحكومية والخاصة والذاتية في مصر.' },
      { question: 'ما هي المستندات المطلوبة للتقديم؟', answer: 'الشهادات المعتمدة وجواز السفر والصور وproof الحساب البنكي.' },
      { question: 'كم يستغرق إجراء التسجيل؟', answer: 'عادة من 7 إلى 14 يوماً حسب الجامعة وال步骤 الإدارية.' },
    ],
    faqEn: [
      { question: 'Do you handle all Egyptian universities?', answer: 'Yes, public, private, and self-financed universities.' },
      { question: 'What documents are needed?', answer: 'Certified certificates, passport, photos, bank proof.' },
      { question: 'How long does enrollment take?', answer: 'Usually 7-14 days depending on university.' },
    ],
    requiredDocuments: ['الشهادات الدراسية المعتمدة مترجمة', 'جواز سفر ساري المفعول', 'صور شخصية (6 صور)', 'إثبات الحساب البنكي', 'خطاب التوصية من المدرسة السابقة (إن وجد)'],
    requiredDocumentsEn: ['Certified academic certificates (translated)', 'Valid passport', '6 photos', 'Bank account proof', 'Recommendation letter from previous school'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#8b5cf6] via-[#a855f7] to-[#d946ef]',
  },
  {
    id: 'e-consulting',
    name: 'الاستشارات الإلكترونية',
    nameEn: 'E-Consulting',
    description: 'استشارات متخصصة في المعاملات الإلكترونية والرقمية مع خبراء معتمدين.',
    descriptionEn: 'Specialized e-consulting with certified experts.',
    fullDescription: 'نقدم استشارات متخصصة في المعاملات الإلكترونية والرقمية مع فريق من الخبراء المعتمدين في مختلف المجالات. نساعدك في اتخاذ قرارات مدروسة لمشاريعك.\n\nفريقنا يشمل خبراء في التجارة الإلكترونية والتسويق الرقمي والأمن السيبراني والتحول الرقمي.\n\nالخدمة تشمل جلسة استشارية مفصلة مع تقرير مكتوب يحتوي على التوصيات والحلول المناسبة.\n\nنسعى لتقديم رؤى استراتيجية تساعدك على تحقيق أهدافك الرقمية.',
    fullDescriptionEn: 'Specialized digital consulting with certified experts and detailed reports.',
    icon: 'MessageSquare',
    category: 'CONSULTATIONS',
    categoryAr: 'الاستشارات',
    price: 150,
    priceNote: 'رسوم الجلسة',
    priceNoteEn: 'Session fee',
    duration: 'حسب الطلب',
    durationEn: 'Upon request',
    features: ['خبراء معتمدون', 'استشارة عبر الإنترنت', 'تقرير مفصل بعد الاستشارة', 'متابعة دورية', 'جلسات مرنة', 'تعدد التخصصات'],
    featuresEn: ['Certified experts', 'Online consultation', 'Detailed report after session', 'Periodic follow-up', 'Flexible sessions', 'Multiple specializations'],
    requirements: ['وصف واضح للمشكلة أو الطلب', 'المستندات ذات الصلة', 'الأهداف المرجوة من الاستشارة'],
    requirementsEn: ['Clear description of the issue', 'Related documents', 'Expected goals from consultation'],
    steps: [
      { title: 'تحديد الموضوع', description: 'نحدد موضوع الاستشارة والخبر المطلوب', icon: 'Search' },
      { title: 'إعداد التحليل', description: 'يقوم الخبير بتحليل وضعك واحتياجاتك', icon: 'FileText' },
      { title: 'جلسة الاستشارة', description: 'نعقد جلسة استشارية مفصلة عبر الإنترنت', icon: 'Video' },
      { title: 'التقرير والتوصيات', description: 'نسلمك تقريراً مكتوباً بالتوصيات والحلول', icon: 'CheckCircle' },
      { title: 'المتابعة', description: 'نوفر متابعة دورية لتطبيق التوصيات', icon: 'Bell' },
    ],
    stepsEn: [
      { title: 'Define Topic', description: 'Set consultation topic and needed expertise', icon: 'Search' },
      { title: 'Prepare Analysis', description: 'Expert analyzes your situation and needs', icon: 'FileText' },
      { title: 'Consultation Session', description: 'Detailed online consultation session', icon: 'Video' },
      { title: 'Report & Recommendations', description: 'Written report with solutions', icon: 'CheckCircle' },
      { title: 'Follow-up', description: 'Periodic follow-up on implementation', icon: 'Bell' },
    ],
    faq: [
      { question: 'كيف تتم جلسة الاستشارة؟', answer: 'عبر الإنترنت via فيديو أو مكالمة في الوقت المحدد.' },
      { question: 'ما هي التخصصات المتاحة؟', answer: 'التجارة الإلكترونية والتسويق الرقمي والأمن السيبراني والتحول الرقمي وغيرهم.' },
      { question: 'كم تبلغ تكلفة الاستشارة؟', answer: 'تبدأ من 150 ر.س للجلسة الواحدة.' },
    ],
    faqEn: [
      { question: 'How is the consultation conducted?', answer: 'Online via video or voice call at scheduled time.' },
      { question: 'What specializations are available?', answer: 'E-commerce, digital marketing, cybersecurity, digital transformation.' },
      { question: 'What is the consultation cost?', answer: 'Starting from 150 SAR per session.' },
    ],
    requiredDocuments: ['وصف واضح للمشكلة أو الطلب', 'المستندات ذات الصلة (إن وجدت)', 'الأهداف المرجوة من الاستشارة', 'أي تقارير سابقة ذات صلة'],
    requiredDocumentsEn: ['Clear description of issue', 'Related documents (if any)', 'Expected consultation goals', 'Previous related reports'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#f97316] via-[#ea580c] to-[#c2410c]',
  },
  {
    id: 'misc-services',
    name: 'خدمات متنوعة',
    nameEn: 'Miscellaneous Services',
    description: 'مجموعة متنوعة من الخدمات المخصصة لتلبية احتياجاتك المختلفة مع ضمان الجودة والسرعة.',
    descriptionEn: 'Diverse services to meet your various needs with quality and speed.',
    fullDescription: 'نقدم مجموعة متنوعة من الخدمات المخصصة لتلبية احتياجاتك المختلفة. إذا لم تجد الخدمة التي تبحث عنها في قائمتنا، تواصل معنا وسن尽力 لمساعدتك.\n\nفريقنا المرن والمحترف يتكيف مع متطلباتك الخاصة ويقدم حلولاً مخصصة تناسب احتياجاتك.\n\nنسعى دائماً لتوسيع خدماتنا لتوفير تجربة متكاملة لعملائنا الكرام.\n\nتواصل معنا اليوم لمناقشة احتياجاتك وسنقدم لك أفضل الحلول المتاحة.',
    fullDescriptionEn: 'Custom services tailored to your specific needs with quality assurance.',
    icon: 'Star',
    category: 'OTHER',
    categoryAr: 'خدمات متنوعة',
    price: 100,
    priceNote: 'يبدأ من',
    priceNoteEn: 'Starting from',
    duration: 'حسب الطلب',
    durationEn: 'Upon request',
    features: ['خدمات متنوعة ومتكاملة', 'أسعار تنافسية', 'جودة عالية مضمونة', 'دعم فني متواصل', 'حلول مخصصة', 'مرونة في التنفيذ'],
    featuresEn: ['Diverse and integrated services', 'Competitive prices', 'High quality guarantee', 'Continuous support', 'Custom solutions', 'Execution flexibility'],
    requirements: ['وصف الخدمة المطلوبة', 'المستندات ذات الصلة حسب الخدمة'],
    requirementsEn: ['Description of required service', 'Related documents per service'],
    steps: [
      { title: 'تواصل معنا', description: 'أرسل لنا تفاصيل احتياجاتك ومتطلباتك', icon: 'MessageSquare' },
      { title: 'تحليل الاحتياجات', description: 'نحلل احتياجاتك ونقترح الحلول المناسبة', icon: 'Search' },
      { title: 'تقديم العرض', description: 'نقدم عرضاً تفصيلياً بالتكلفة والجدول الزمني', icon: 'FileText' },
      { title: 'التنفيذ والتسليم', description: 'ننجز الخدمة ونسلمك النتيجة النهائية', icon: 'Package' },
    ],
    stepsEn: [
      { title: 'Contact Us', description: 'Send us your requirements details', icon: 'MessageSquare' },
      { title: 'Analyze Needs', description: 'We analyze and suggest suitable solutions', icon: 'Search' },
      { title: 'Submit Proposal', description: 'Detailed proposal with cost and timeline', icon: 'FileText' },
      { title: 'Execute & Deliver', description: 'Complete service and deliver final result', icon: 'Package' },
    ],
    faq: [
      { question: 'ما هي الخدمات المتنوعة المتاحة؟', answer: 'نقدم خدمات مخصصة حسب احتياجات العميل. تواصل معنا لمناقشة متطلباتك.' },
      { question: 'كيف أطلب خدمة مخصصة؟', answer: 'تواصل معنا عبر المنصة وصف احتياجاتك وسنقدم لك عرضاً مناسباً.' },
      { question: 'ما هي المدة الزمنية للتنفيذ؟', answer: 'تعتمد على طبيعة الخدمة، ونحدد المدة في عرضنا التفصيلي.' },
    ],
    faqEn: [
      { question: 'What miscellaneous services are available?', answer: 'Custom services based on client needs. Contact us to discuss.' },
      { question: 'How do I request a custom service?', answer: 'Contact us via the platform and describe your needs.' },
      { question: 'What is the execution timeline?', answer: 'Depends on service nature, specified in our detailed proposal.' },
    ],
    requiredDocuments: ['وصف الخدمة المطلوبة بالتفصيل', 'أي مستندات ذات الصلة', 'الميزانية المتوقعة والجدول الزمني المرجو'],
    requiredDocumentsEn: ['Detailed service description', 'Any related documents', 'Expected budget and timeline'],
    isPopular: false,
    isActive: true,
    gradient: 'from-[#6366f1] via-[#4f46e5] to-[#4338ca]',
  },
];
